"""Convert the legacy events.json into SQL for app.events + app.event_sources.

Usage (from services/api):
    uv run python -m fhc_api.legacy_import ../../events.json > ../../supabase/seed_legacy_events.sql

Mapping: docs/architecture/DATA_MODEL.md §6. Output is idempotent (ON CONFLICT DO NOTHING).
"""

import json
import re
import sys
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any

from fhc_api.common.normalize import normalize_url

FORMATS = {"Yüz yüze": "in_person", "Online": "online", "Hibrit": "hybrid"}


@dataclass(frozen=True)
class Location:
    city: str | None = None
    country: str | None = None
    venue: str | None = None


# Free-text `location` values cannot be parsed reliably, so each legacy record is mapped by hand.
LOCATIONS: dict[str, Location] = {
    "grid-up-hackathon": Location(),
    "zemin360-hackathon": Location(city="İstanbul", country="TR"),
    "borsa-istanbul-fintech-hackathon": Location(
        city="İstanbul", country="TR", venue="Borsa İstanbul"
    ),
    "greece-turkiye-hackathon-2026": Location(venue="Atina (yarı final) / İstanbul (final)"),
    "devnetwork-api-cloud-ai-hackathon-2026": Location(city="Santa Clara", country="US"),
    "oneaquahealth-ieee-global-hackathon": Location(),
}


@dataclass(frozen=True)
class EventRow:
    slug: str
    title: str
    organizer: str | None
    summary: str | None
    description: str | None
    format: str | None
    location: Location
    start_date: date | None
    application_deadline: date | None
    team_min: int | None
    team_max: int | None
    official_url: str
    official_url_normalized: str


def parse_team_size(value: str | None) -> tuple[int | None, int | None]:
    if not value:
        return None, None
    match = re.search(r"(\d+)\s*[-\u2013]\s*(\d+)", value) or re.search(r"(\d+)", value)
    if not match:
        return None, None
    numbers = [int(group) for group in match.groups()]
    return numbers[0], numbers[-1]


def first_sentence(text: str | None, limit: int = 300) -> str | None:
    if not text:
        return None
    match = re.match(r"(.+?[.!?])(\s|$)", text)
    sentence = (match.group(1) if match else text).strip()
    return sentence if len(sentence) <= limit else sentence[: limit - 1].rstrip() + "…"


def parse_date(value: str | None) -> date | None:
    return date.fromisoformat(value) if value else None


def to_row(raw: dict[str, Any]) -> EventRow:
    slug = str(raw["id"])
    if slug not in LOCATIONS:
        raise ValueError(f"No location mapping for legacy event {slug!r}")
    raw_format = raw.get("format")
    if raw_format and raw_format not in FORMATS:
        raise ValueError(f"Unknown format {raw_format!r} in {slug!r}")
    team_min, team_max = parse_team_size(raw.get("teamSize"))
    url = str(raw["url"])
    return EventRow(
        slug=slug,
        title=str(raw["name"]),
        organizer=raw.get("organizer") or None,
        summary=first_sentence(raw.get("description")),
        description=raw.get("description") or None,
        format=FORMATS.get(raw_format) if raw_format else None,
        location=LOCATIONS[slug],
        start_date=parse_date(raw.get("eventDate")),
        application_deadline=parse_date(raw.get("deadline")),
        team_min=team_min,
        team_max=team_max,
        official_url=url,
        official_url_normalized=normalize_url(url),
    )


def sql_literal(value: object) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def to_sql(rows: list[EventRow]) -> str:
    lines = [
        "-- Generated by fhc_api.legacy_import from events.json. Do not edit by hand.",
        "insert into app.events (",
        "  slug, title, organizer, summary, description, format, city, country, venue,",
        "  start_date, application_deadline, team_min, team_max, official_url,",
        "  official_url_normalized, status, verification_status, published_at",
        ") values",
    ]
    values = []
    for row in rows:
        fields = [
            row.slug, row.title, row.organizer, row.summary, row.description,
            row.format, row.location.city, row.location.country, row.location.venue,
            row.start_date, row.application_deadline, row.team_min, row.team_max,
            row.official_url, row.official_url_normalized,
        ]  # fmt: skip
        rendered = ", ".join(sql_literal(field) for field in fields)
        values.append(f"  ({rendered}, 'published', 'unverified', now())")
    lines.append(",\n".join(values))
    lines.append("on conflict (slug) do nothing;")
    lines.append("")
    lines.append("insert into app.event_sources (event_id, source_id, url, url_normalized, role)")
    lines.append("select e.id, s.id, e.official_url, e.official_url_normalized, 'official'")
    lines.append("from app.events e cross join app.sources s")
    lines.append("where s.name = 'Manual entry'")
    slugs = ", ".join(sql_literal(row.slug) for row in rows)
    lines.append(f"  and e.slug in ({slugs})")
    lines.append("on conflict (event_id, url_normalized) do nothing;")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    raw_events = json.loads(Path(argv[1]).read_text(encoding="utf-8"))
    rows = [to_row(item) for item in raw_events]
    sys.stdout.reconfigure(encoding="utf-8", newline="\n")  # type: ignore[union-attr]
    sys.stdout.write(to_sql(rows))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
