/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overview */
        get: operations["get_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events"];
        put?: never;
        /** Create Event */
        post: operations["create_event"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["get_event"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Event */
        patch: operations["update_event"];
        trace?: never;
    };
    "/events/{event_id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition Event */
        post: operations["transition_event"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event Review */
        get: operations["get_event_review"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Event Sources */
        get: operations["list_event_sources"];
        put?: never;
        /** Add Event Source */
        post: operations["add_event_source"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}/sources/{event_source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Event Source */
        delete: operations["remove_event_source"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources"];
        put?: never;
        /** Create Source */
        post: operations["create_source"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Source */
        patch: operations["update_source"];
        trace?: never;
    };
    "/community-applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Community Applications */
        get: operations["list_community_applications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/community-applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Community Application */
        patch: operations["update_community_application"];
        trace?: never;
    };
    "/team-applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Team Applications */
        get: operations["list_team_applications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team-applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Team Application */
        patch: operations["update_team_application"];
        trace?: never;
    };
    "/system/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Database
         * @description 200 when a query round-trip succeeds; 503 `database unavailable` otherwise.
         */
        get: operations["check_database"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llm/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Llm Check */
        get: operations["llm_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telegram/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Telegram Check */
        get: operations["telegram_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin-bot/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Bot Status */
        get: operations["admin_bot_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** AdminBotStatus */
        AdminBotStatus: {
            /**
             * Enabled
             * @description TELEGRAM_ADMIN_ENABLED
             */
            enabled: boolean;
            /**
             * State
             * @description disabled (default), config_error (enabled but not started), stopped (not started yet or shut down), starting, running, error (retrying with backoff)
             * @enum {string}
             */
            state: "disabled" | "config_error" | "stopped" | "starting" | "running" | "error";
            /**
             * Running
             * @description The background thread is alive
             */
            running: boolean;
            /** Config Error */
            config_error?: string | null;
            /** Bot Username */
            bot_username?: string | null;
            /** Allowlist Size */
            allowlist_size: number;
            /** Max Press Age Hours */
            max_press_age_hours: number | null;
            /** Scan Interval Seconds */
            scan_interval_seconds: number | null;
            /** Last Poll At */
            last_poll_at?: string | null;
            /** Last Scan At */
            last_scan_at?: string | null;
            /** Last Error */
            last_error?: string | null;
            /** Last Error At */
            last_error_at?: string | null;
            /**
             * Pending Notifications
             * @description Sent messages still waiting for a decision; null when the DB is down
             */
            pending_notifications: number | null;
            /**
             * Pending Replies
             * @description Open reason prompts
             */
            pending_replies: number | null;
        };
        /** ApplicationStatusUpdate */
        ApplicationStatusUpdate: {
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "contacted" | "accepted" | "declined" | "spam";
        };
        /** CommunityApplicationOut */
        CommunityApplicationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name: string;
            /** University */
            university: string | null;
            /** Field Of Study */
            field_of_study: string | null;
            /** Year Of Study */
            year_of_study: string | null;
            /** Interests */
            interests: string[];
            /** Experience Level */
            experience_level: string | null;
            /** Looking For */
            looking_for: string | null;
            /**
             * Preferred Channel
             * @enum {string}
             */
            preferred_channel: "telegram" | "whatsapp";
            /** Telegram Username */
            telegram_username: string | null;
            /** Phone */
            phone: string | null;
            /** Message */
            message: string | null;
            /** Consent Version */
            consent_version: string;
            /**
             * Consented At
             * Format: date-time
             */
            consented_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "contacted" | "accepted" | "declined" | "spam";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CommunityApplicationPage */
        CommunityApplicationPage: {
            /** Items */
            items: components["schemas"]["CommunityApplicationOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** DbCheckOut */
        DbCheckOut: {
            /** Ok */
            ok: boolean;
            /** Latency Ms */
            latency_ms: number;
            /** Role */
            role: string;
            /** Server Version */
            server_version: string;
        };
        /** DuplicateCandidate */
        DuplicateCandidate: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "in_review" | "approved" | "published" | "archived" | "rejected";
            /** Matches */
            matches: ("official_url" | "title_and_start_date")[];
        };
        /** ErrorOut */
        ErrorOut: {
            /** Detail */
            detail: string;
        };
        /** EventCreate */
        EventCreate: {
            /** Title */
            title: string;
            /** Organizer */
            organizer?: string | null;
            /** Summary */
            summary?: string | null;
            /** Description */
            description?: string | null;
            /** Categories */
            categories?: string[];
            /** Technologies */
            technologies?: string[];
            /** Format */
            format?: ("in_person" | "online" | "hybrid") | null;
            /** City */
            city?: string | null;
            /** Country */
            country?: string | null;
            /** Venue */
            venue?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Application Deadline */
            application_deadline?: string | null;
            /**
             * Timezone
             * @default Europe/Istanbul
             */
            timezone: string;
            /** Eligibility */
            eligibility?: string | null;
            /** Team Min */
            team_min?: number | null;
            /** Team Max */
            team_max?: number | null;
            /** Prize Pool */
            prize_pool?: number | string | null;
            /** Currency */
            currency?: string | null;
            /** Is Free */
            is_free?: boolean | null;
            /** Official Url */
            official_url: string;
            /** Application Url */
            application_url?: string | null;
            /** Poster Url */
            poster_url?: string | null;
            /** Banner Url */
            banner_url?: string | null;
            /** Organizer Logo Url */
            organizer_logo_url?: string | null;
            /**
             * Verification Status
             * @default unverified
             * @enum {string}
             */
            verification_status: "unverified" | "partially_verified" | "verified";
            /** Internal Notes */
            internal_notes?: string | null;
        };
        /** EventOut */
        EventOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Organizer */
            organizer: string | null;
            /** Summary */
            summary: string | null;
            /** Description */
            description: string | null;
            /** Categories */
            categories: string[];
            /** Technologies */
            technologies: string[];
            /** Format */
            format: ("in_person" | "online" | "hybrid") | null;
            /** City */
            city: string | null;
            /** Country */
            country: string | null;
            /** Venue */
            venue: string | null;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
            /** Application Deadline */
            application_deadline: string | null;
            /** Timezone */
            timezone: string;
            /** Eligibility */
            eligibility: string | null;
            /** Team Min */
            team_min: number | null;
            /** Team Max */
            team_max: number | null;
            /** Prize Pool */
            prize_pool: string | null;
            /** Currency */
            currency: string | null;
            /** Is Free */
            is_free: boolean | null;
            /** Official Url */
            official_url: string;
            /** Official Url Normalized */
            official_url_normalized: string;
            /** Application Url */
            application_url: string | null;
            /** Poster Url */
            poster_url: string | null;
            /** Banner Url */
            banner_url: string | null;
            /** Organizer Logo Url */
            organizer_logo_url: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "in_review" | "approved" | "published" | "archived" | "rejected";
            /**
             * Verification Status
             * @enum {string}
             */
            verification_status: "unverified" | "partially_verified" | "verified";
            /** Duplicate Of */
            duplicate_of: string | null;
            /** Internal Notes */
            internal_notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Discovered At */
            discovered_at: string | null;
            /** Verified At */
            verified_at: string | null;
            /** Published At */
            published_at: string | null;
            /** Archived At */
            archived_at: string | null;
            /**
             * Allowed Actions
             * @description Transitions the state machine allows from the current status. Guards (required fields, dates, URL) are checked when the action is sent.
             */
            allowed_actions: ("submit" | "approve" | "reject" | "request_changes" | "publish" | "unpublish" | "archive" | "reopen")[];
        };
        /** EventPage */
        EventPage: {
            /** Items */
            items: components["schemas"]["EventOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** EventSourceCreate */
        EventSourceCreate: {
            /** Url */
            url: string;
            /**
             * Role
             * @enum {string}
             */
            role: "official" | "registration" | "discovery" | "announcement";
            /** Source Id */
            source_id?: string | null;
        };
        /** EventSourceOut */
        EventSourceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /** Source Id */
            source_id: string | null;
            /** Source Name */
            source_name: string | null;
            /** Source Tier */
            source_tier: number | null;
            /** Url */
            url: string;
            /** Url Normalized */
            url_normalized: string;
            /**
             * Role
             * @enum {string}
             */
            role: "official" | "registration" | "discovery" | "announcement";
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Last Checked At */
            last_checked_at: string | null;
            /** Last Http Status */
            last_http_status: number | null;
            /** Content Hash */
            content_hash: string | null;
        };
        /** EventTransition */
        EventTransition: {
            /**
             * Action
             * @enum {string}
             */
            action: "submit" | "approve" | "reject" | "request_changes" | "publish" | "unpublish" | "archive" | "reopen";
            /**
             * Reason
             * @description Required for `reject`. When given, it is appended to `internal_notes`.
             */
            reason?: string | null;
        };
        /**
         * EventUpdate
         * @description Partial update. `null` clears an optional field; the fields in `not_null_fields`
         *     reject it. The slug is never changed after creation: it is the public URL.
         */
        EventUpdate: {
            /** Title */
            title?: string | null;
            /** Organizer */
            organizer?: string | null;
            /** Summary */
            summary?: string | null;
            /** Description */
            description?: string | null;
            /** Categories */
            categories?: string[] | null;
            /** Technologies */
            technologies?: string[] | null;
            /** Format */
            format?: ("in_person" | "online" | "hybrid") | null;
            /** City */
            city?: string | null;
            /** Country */
            country?: string | null;
            /** Venue */
            venue?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Application Deadline */
            application_deadline?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Eligibility */
            eligibility?: string | null;
            /** Team Min */
            team_min?: number | null;
            /** Team Max */
            team_max?: number | null;
            /** Prize Pool */
            prize_pool?: number | string | null;
            /** Currency */
            currency?: string | null;
            /** Is Free */
            is_free?: boolean | null;
            /** Official Url */
            official_url?: string | null;
            /** Application Url */
            application_url?: string | null;
            /** Poster Url */
            poster_url?: string | null;
            /** Banner Url */
            banner_url?: string | null;
            /** Organizer Logo Url */
            organizer_logo_url?: string | null;
            /** Verification Status */
            verification_status?: ("unverified" | "partially_verified" | "verified") | null;
            /** Internal Notes */
            internal_notes?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Service */
            service: string;
        };
        /** HeartbeatOut */
        HeartbeatOut: {
            /**
             * Source
             * @enum {string}
             */
            source: "vercel_cron" | "github_actions";
            /** Last Seen At */
            last_seen_at: string | null;
            /**
             * Stale
             * @description Never seen, or last seen more than 48 hours ago
             */
            stale: boolean;
        };
        /** LLMCheckResponse */
        LLMCheckResponse: {
            health: components["schemas"]["ProviderHealth"];
            test?: components["schemas"]["LLMCheckTest"] | null;
        };
        /**
         * LLMCheckSample
         * @description Fixed 3-field schema for the connectivity test.
         */
        LLMCheckSample: {
            /** Event Name */
            event_name: string;
            /** City */
            city: string;
            /** Year */
            year: number;
        };
        /** LLMCheckTest */
        LLMCheckTest: {
            /** Ok */
            ok: boolean;
            /** Latency Ms */
            latency_ms: number;
            output?: components["schemas"]["LLMCheckSample"] | null;
            /** Error */
            error?: string | null;
        };
        /** OverviewOut */
        OverviewOut: {
            /** In Review */
            in_review: number;
            /**
             * Published Upcoming
             * @description Published, last day (end or start) >= today
             */
            published_upcoming: number;
            /**
             * Closing Within 7 Days
             * @description Published, deadline within today..today+7
             */
            closing_within_7_days: number;
            /** New Community Applications */
            new_community_applications: number;
            /** New Team Applications */
            new_team_applications: number;
            /** Heartbeats */
            heartbeats: components["schemas"]["HeartbeatOut"][];
        };
        /** ProviderHealth */
        ProviderHealth: {
            /** Provider */
            provider: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "not_running" | "model_missing" | "error";
            /** Configured Model */
            configured_model: string;
            /** Installed Models */
            installed_models?: string[];
            /** Message */
            message: string;
        };
        /** ReviewOut */
        ReviewOut: {
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /** Signals */
            signals: components["schemas"]["Signal"][];
            /** Duplicates */
            duplicates: components["schemas"]["DuplicateCandidate"][];
            /** Sources By Tier */
            sources_by_tier: components["schemas"]["TierCount"][];
        };
        /** Signal */
        Signal: {
            /**
             * Key
             * @enum {string}
             */
            key: "official_url_reachable" | "registration_url_present" | "dates_coherent" | "deadline_missing" | "deadline_passed" | "possible_duplicate" | "supporting_sources";
            /**
             * Status
             * @enum {string}
             */
            status: "pass" | "warn" | "fail" | "info";
            /** Detail */
            detail: string;
            /**
             * Blocks Approval
             * @description True when this failing check also makes `approve`/`publish` return 409
             */
            blocks_approval: boolean;
        };
        /** SourceCreate */
        SourceCreate: {
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "organizer_site" | "event_platform" | "social" | "aggregator" | "university" | "community" | "manual";
            /**
             * Tier
             * @enum {integer}
             */
            tier: 1 | 2 | 3 | 4;
            /** Base Url */
            base_url?: string | null;
            /**
             * Retrieval Method
             * @default manual
             * @enum {string}
             */
            retrieval_method: "manual" | "api" | "json_endpoint" | "rss" | "html" | "browser";
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Requires Js
             * @default false
             */
            requires_js: boolean;
            /** Notes */
            notes?: string | null;
        };
        /** SourceOut */
        SourceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "organizer_site" | "event_platform" | "social" | "aggregator" | "university" | "community" | "manual";
            /** Tier */
            tier: number;
            /** Base Url */
            base_url: string | null;
            /**
             * Retrieval Method
             * @enum {string}
             */
            retrieval_method: "manual" | "api" | "json_endpoint" | "rss" | "html" | "browser";
            /** Enabled */
            enabled: boolean;
            /** Requires Js */
            requires_js: boolean;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SourceUpdate */
        SourceUpdate: {
            /** Name */
            name?: string | null;
            /** Kind */
            kind?: ("organizer_site" | "event_platform" | "social" | "aggregator" | "university" | "community" | "manual") | null;
            /** Tier */
            tier?: (1 | 2 | 3 | 4) | null;
            /** Base Url */
            base_url?: string | null;
            /** Retrieval Method */
            retrieval_method?: ("manual" | "api" | "json_endpoint" | "rss" | "html" | "browser") | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Requires Js */
            requires_js?: boolean | null;
            /** Notes */
            notes?: string | null;
        };
        /** TeamApplicationOut */
        TeamApplicationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name: string;
            /** Affiliation */
            affiliation: string | null;
            /** Areas */
            areas: string[];
            /** Skills */
            skills: string | null;
            /** Github Url */
            github_url: string | null;
            /** Linkedin Url */
            linkedin_url: string | null;
            /** Availability */
            availability: string | null;
            /** Motivation */
            motivation: string | null;
            /** Consent Version */
            consent_version: string;
            /**
             * Consented At
             * Format: date-time
             */
            consented_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "contacted" | "accepted" | "declined" | "spam";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TeamApplicationPage */
        TeamApplicationPage: {
            /** Items */
            items: components["schemas"]["TeamApplicationOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** TelegramCheckResult */
        TelegramCheckResult: {
            /**
             * Status
             * @enum {string}
             */
            status: "not_configured" | "invalid_token" | "chat_not_found" | "bot_not_admin" | "missing_rights" | "ok" | "error";
            /** Message */
            message: string;
            /** Bot Username */
            bot_username?: string | null;
            /** Chat Title */
            chat_title?: string | null;
            /** Chat Type */
            chat_type?: string | null;
            /** Missing Rights */
            missing_rights?: string[];
            /** Missing Optional Rights */
            missing_optional_rights?: string[];
            /** Excess Rights */
            excess_rights?: string[];
        };
        /** TierCount */
        TierCount: {
            /**
             * Tier
             * @description Source tier 1-4; null for URLs without a source
             */
            tier: number | null;
            /** Count */
            count: number;
        };
        /**
         * UnprocessableOut
         * @description 422: a rule message (string) from the API, or FastAPI's list of field errors.
         */
        UnprocessableOut: {
            /** Detail */
            detail: string | {
                [key: string]: unknown;
            }[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    get_overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    list_events: {
        parameters: {
            query?: {
                /** @description Repeat to match several */
                status?: ("draft" | "in_review" | "approved" | "published" | "archived" | "rejected")[] | null;
                /** @description Only published events whose last day is today or later */
                upcoming?: boolean;
                /** @description Only published events with a deadline in N days */
                closing_within_days?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_event: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnprocessableOut"];
                };
            };
        };
    };
    get_event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnprocessableOut"];
                };
            };
        };
    };
    transition_event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTransition"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnprocessableOut"];
                };
            };
        };
    };
    get_event_review: {
        parameters: {
            query?: {
                /** @description Fetch the official URL (network, up to ~10 s per hop) */
                check_url?: boolean;
            };
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_event_sources: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventSourceOut"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_event_source: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventSourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventSourceOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnprocessableOut"];
                };
            };
        };
    };
    remove_event_source: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
                event_source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    create_source: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnprocessableOut"];
                };
            };
        };
    };
    update_source: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnprocessableOut"];
                };
            };
        };
    };
    list_community_applications: {
        parameters: {
            query?: {
                /** @description Repeat to match several */
                status?: ("new" | "contacted" | "accepted" | "declined" | "spam")[] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityApplicationPage"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_community_application: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityApplicationOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_team_applications: {
        parameters: {
            query?: {
                /** @description Repeat to match several */
                status?: ("new" | "contacted" | "accepted" | "declined" | "spam")[] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamApplicationPage"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_team_application: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamApplicationOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_database: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DbCheckOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    llm_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMCheckResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    telegram_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramCheckResult"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    admin_bot_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminBotStatus"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
}
